### ISSUE TITLE
autojar is... something?

### ISSUE THREAD

**Issue by dirkraft** [blacklocus/rds-echo#7]
I see this running the rds-echo binary on both Mac and Ubuntu Linux. Works fine in IntelliJ.

```
19:24:04 INFO Reading configuration from rdsecho.properties
19:24:04 INFO Locating latest Echo managed instance (tagged with rdsecho:development:managed=true) in stage 'rebooted' (tagged with rdsecho:development:stage=rebooted).
19:24:06 INFO   Located echo-managed instance with identifier development-2015-02-03
19:24:06 INFO Reading current DNS records
19:24:06 INFO   Found corresponding HostedZone. name: blacklocus.com. id: /hostedzone/ZABCDEFG12345
[Fatal Error] :1:1: Premature end of file.
Exception in thread "main" com.amazonaws.AmazonServiceException: Unable to unmarshall error response () (Service: AmazonRoute53; Status Code: 400; Error Code: 400 Bad Request; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.route53.AmazonRoute53Client.invoke(AmazonRoute53Client.java:2127)
	at com.amazonaws.services.route53.AmazonRoute53Client.listResourceRecordSets(AmazonRoute53Client.java:643)
	at com.github.blacklocus.rdsecho.utl.Route53Find$2.get(Route53Find.java:105)
	at com.github.blacklocus.rdsecho.utl.Route53Find$2.get(Route53Find.java:94)
	at com.github.blacklocus.rdsecho.utl.PagingIterable.<init>(PagingIterable.java:39)
	at com.github.blacklocus.rdsecho.utl.Route53Find.resourceRecordSets(Route53Find.java:94)
	at com.github.blacklocus.rdsecho.utl.Route53Find.resourceRecordSet(Route53Find.java:90)
	at com.github.blacklocus.rdsecho.EchoPromote.traverseStage(EchoPromote.java:66)
	at com.github.blacklocus.rdsecho.AbstractEchoIntermediateStage.call(AbstractEchoIntermediateStage.java:102)
	at com.github.blacklocus.rdsecho.EchoPromote.call(EchoPromote.java:47)
	at com.github.blacklocus.rdsecho.AbstractEchoIntermediateStage.call(AbstractEchoIntermediateStage.java:39)
	at com.github.blacklocus.rdsecho.Echo.main(Echo.java:84)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:125)
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:132)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:80)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:40)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1045)
	... 15 more
```

**Comment by dirkraft** [comment]
This only occurred when attempting to `rds-echo promote`
